### ISSUE TITLE
Attempt to invoke virtual method `addView`?

### ISSUE THREAD

**Issue by htorbov** [rahadur/capacitor-admob#24]
Hi @rahadur, It works perfectly on iOS, but on Android I have an issue (clean install on a new project with latest versions of everything).

Android Debug log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.foodprep.ranger, PID: 5575
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
        at app.xplatform.capacitor.plugins.AdMob$2.run(AdMob.java:206)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Line 206 of AdMob.java:
```
mViewGroup.addView(mAdViewLayout);
```

**Comment by htorbov** [comment]
BTW, I'm using this way to run the banner, because I'm using non-TypeScript Vue (it works on iOS):
```ts
this.$Plugins.AdMob.showBanner({ adId: 'XXX', adSize: AdSize.BANNER, position: AdPosition.BOTTOM_CENTER }).then(async (response) => {
  //
}).catch(async (response) => {
  //
})
```
