### ISSUE TITLE
App crashes when launching on Android

### ISSUE THREAD

**Issue by NP-Systems** [rahadur/capacitor-admob#59]
Hi there, I installed the plugin  with Ionic capacitor 2.1.2 on Android API28, and got an error saying that  it cannot resolve symbol 'design' and a build error of 
`error: package android.support.design.widget does not exist”.`

Altough I fixed the error thanks for this thread => https://github.com/rahadur/capacitor-admob/issues/35 , my app crashes when launching .

I think this is because the plugin uses 'implementation 'com.android.support:appcompat-v7:27.1.1'' in build.gradle . 
Can you please help me how to fix this issue ? I think I need to change 'com.android.support:appcompat-v7:27.1.1' to the one with AndroidX.

Thanks,

-package.json 
  => "capacitor-admob": "^0.1.0",
-ionic info 
`Ionic:
   Ionic CLI                     : 6.4.1 
  Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0
Capacitor:
   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.1.2
`
<img width="947" alt="スクリーンショット 2020-06-01 20 13 49" src="https://user-images.githubusercontent.com/52349737/83403897-85ef3800-a444-11ea-9afe-4dc9a2d6ceea.png">

**Comment by NP-Systems** [comment]
In my log cat, it says

`2020-06-01 20:21:30.181 29028-29028/com.app.id E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.***.***, PID: 29028
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.id/com.app.id.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/com.app.id-D95nAHlVz8LdpAH0PqdCQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.id-D95nAHlVz8LdpAH0PqdCQw==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:55)
        at com.app.id.MainActivity.onCreate(MainActivity.java:17)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by NP-Systems** [comment]
I finally resolved...
With reading logcat carefully,  
```
npm install jetifier
npx jetify
npx cap sync android
```
worked.
https://github.com/ionic-team/capacitor/issues/2810

Thank you !!

**Comment by NP-Systems** [comment]
https://github.com/ionic-team/capacitor/issues/2810
